In [1]:
import sys
sys.path.append('..')
from bicm.graph_classes import *
from bicm.network_functions import *
# import bicm
# from bicm import *
import numpy as np

In [2]:
weighted_biadmat = np.random.randint(6, size=(100,200))

In [3]:
myGraph = BipartiteGraph(biadjacency=weighted_biadmat)

Weighted model mode


In [4]:
myGraph.solve_tool()

/home/matteo/miniconda3/envs/bicm/lib/python3.10/site-packages/numba/core/utils.py:612: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
/home/matteo/Sony/BiCM/bicm/models_functions.py:30: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  step_fun = args[0]
/home/matteo/Sony/BiCM/bicm/models_functions.py:31: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  arg_step_fun = args[1]


max rows error = 3.410605131648481e-13
max columns error = 3.979039320256561e-13
total error = 2.560796019679401e-11
Solver converged.


/home/matteo/miniconda3/envs/bicm/lib/python3.10/site-packages/numba/core/utils.py:612: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",


In [5]:
myGraph.avg_mat

array([[2.39303034, 3.00184411, 2.41573224, ..., 2.96697946, 2.64391944,
        3.22379138],
       [2.07352773, 2.54020215, 2.09133041, ..., 2.51406757, 2.26852401,
        2.70494606],
       [2.27032207, 2.82195344, 2.29107385, ..., 2.79063508, 2.49887158,
        3.02056097],
       ...,
       [2.21445183, 2.74112973, 2.23434402, ..., 2.7113447 , 2.43319232,
        2.92968859],
       [2.02072632, 2.4659825 , 2.0377751 , ..., 2.44113805, 2.20719125,
        2.62234741],
       [2.14220033, 2.63759392, 2.16100716, ..., 2.60971869, 2.34858945,
        2.81367421]])

In [19]:
myGraph.get_weighted_pvals_mat()

array([[0.7052782 , 0.7501152 , 0.50018418, ..., 0.41837311, 0.20109314,
        0.25901347],
       [0.45514044, 0.51484967, 0.20946377, ..., 0.36618497, 1.        ,
        0.20743575],
       [1.        , 0.54516618, 0.48462177, ..., 0.54197861, 0.18581453,
        0.56441937],
       ...,
       [0.47459005, 1.        , 1.        , ..., 0.73055588, 0.35598764,
        0.30892517],
       [0.20025551, 0.50620595, 0.20248951, ..., 0.35700207, 0.22431609,
        0.72393592],
       [0.68175167, 0.72509301, 0.21843534, ..., 1.        , 0.24198074,
        0.73778568]])

In [20]:
myGraph.get_rca_matrix(significance=0.15)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)