In [1]:
import sys
sys.path.append('..')
from bicm.graph_classes import *
from bicm.network_functions import *
# import bicm
# from bicm import *
import numpy as np

In [16]:
weighted_biadmat = np.random.randint(6, size=(100,200))

In [17]:
myGraph = BipartiteGraph(biadjacency=weighted_biadmat)

Weighted model mode


In [18]:
myGraph.solve_tool()

max rows error = 9.926393431669567e-07
max columns error = 4.926359906676225e-07
total error = 7.291955705568398e-05
Solver converged.


/home/matteo/miniconda3/envs/bicm/lib/python3.10/site-packages/numba/core/utils.py:612: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",


In [19]:
myGraph.avg_mat

array([[2.45378042, 2.46379186, 2.55388938, ..., 2.51384728, 2.46379186,
        3.11423205],
       [2.5605491 , 2.57132047, 2.66837937, ..., 2.6252162 , 2.57132047,
        3.27700488],
       [2.47806036, 2.48824223, 2.57989982, ..., 2.53915853, 2.48824223,
        3.15100932],
       ...,
       [2.40519551, 2.41487012, 2.50188644, ..., 2.46322482, 2.41487012,
        3.04105591],
       [2.64778265, 2.65919505, 2.76213634, ..., 2.71633358, 2.65919505,
        3.4120372 ],
       [2.43435045, 2.44422652, 2.53308532, ..., 2.49359828, 2.44422652,
        3.08490122]])

In [20]:
myGraph.get_weighted_pvals_mat()

array([[0.50475653, 1.        , 0.19164208, ..., 0.36615758, 0.18207954,
        0.43369714],
       [0.19234489, 0.71999152, 0.72740006, ..., 0.72415438, 0.5183878 ,
        1.        ],
       [1.        , 0.25890717, 1.        , ..., 1.        , 0.18468435,
        0.25204605],
       ...,
       [0.24890483, 0.50007964, 0.51042398, ..., 0.18201905, 0.25007965,
        0.32071419],
       [0.2775962 , 1.        , 0.39575986, ..., 0.53424052, 0.72671585,
        0.5980661 ],
       [1.        , 0.25362904, 0.71696127, ..., 0.71376217, 0.50361597,
        1.        ]])

In [21]:
myGraph.get_rca_validated_matrix(significance=0.15)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [24]:
myGraph.solve_tool(model='bicwcm')

max rows error = 2.9294263640622376e-05
max columns error = 2.8716272026940715e-08
total error = 0.00010308714715279166
Solver converged.


In [25]:
weighted_biadmat = weighted_biadmat.astype(float) / 2

In [26]:
myGraph = BipartiteGraph(biadjacency=weighted_biadmat)

Weighted model mode


In [27]:
from bicm.models_functions import *

In [28]:
myGraph.solve_tool()

max rows error = 7.650068994280446e-06
max columns error = 7.1326269335258985e-09
total error = 2.560802640516613e-05
Solver converged.


In [29]:
myGraph.avg_mat

array([[1.22690109, 1.2319062 , 1.27694726, ..., 1.25693012, 1.2319062 ,
        1.55696295],
       [1.27995722, 1.28540553, 1.33452162, ..., 1.31267419, 1.28540553,
        1.64341096],
       [1.23896995, 1.24407421, 1.29002604, ..., 1.26960005, 1.24407421,
        1.57645038],
       ...,
       [1.20274481, 1.20755438, 1.25080109, ..., 1.23158911, 1.20755438,
        1.51826631],
       [1.32327536, 1.32909953, 1.38167982, ..., 1.35827459, 1.32909953,
        1.71551591],
       [1.21724154, 1.22216798, 1.26648696, ..., 1.24679389, 1.22216798,
        1.54143995]])

In [30]:
myGraph.get_weighted_pvals_mat()

array([[0.44261205, 1.        , 0.14116946, ..., 0.30319359, 0.13141759,
        0.38158789],
       [0.1418209 , 0.67774627, 0.68751881, ..., 0.68324496, 0.45934   ,
        1.        ],
       [1.        , 0.20036369, 1.        , ..., 1.        , 0.13405214,
        0.20477546],
       ...,
       [0.18959537, 0.43686981, 0.44955924, ..., 0.13134895, 0.19085523,
        0.2678597 ],
       [0.22060065, 1.        , 0.33768728, ..., 0.47891691, 0.68646877,
        0.55826862],
       [1.        , 0.19467257, 0.6738196 , ..., 0.66963091, 0.44121715,
        1.        ]])

In [32]:
myGraph.get_weighted_pvals_mat()

array([[0.44261205, 1.        , 0.14116946, ..., 0.30319359, 0.13141759,
        0.38158789],
       [0.1418209 , 0.67774627, 0.68751881, ..., 0.68324496, 0.45934   ,
        1.        ],
       [1.        , 0.20036369, 1.        , ..., 1.        , 0.13405214,
        0.20477546],
       ...,
       [0.18959537, 0.43686981, 0.44955924, ..., 0.13134895, 0.19085523,
        0.2678597 ],
       [0.22060065, 1.        , 0.33768728, ..., 0.47891691, 0.68646877,
        0.55826862],
       [1.        , 0.19467257, 0.6738196 , ..., 0.66963091, 0.44121715,
        1.        ]])

In [31]:
myGraph.get_rca_validated_matrix(significance=0.15)

array([[0, 0, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [33]:
myGraph.solve_tool(model='biwcm')

/home/matteo/miniconda3/envs/bicm/lib/python3.10/site-packages/numba/core/utils.py:612: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
/home/matteo/Sony/BiCM/bicm/models_functions.py:30: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  step_fun = args[0]
/home/matteo/Sony/BiCM/bicm/models_functions.py:31: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  arg_step_fun = args[1]


max rows error = 3.094647240686754e-07
max columns error = 6.984549543176399e-07
total error = 2.276719918370418e-05
Solver converged.


/home/matteo/miniconda3/envs/bicm/lib/python3.10/site-packages/numba/core/utils.py:612: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
